name: plan
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1
  equatable: ^2.0.5
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  get_it: ^7.6.4
  envied: ^0.5.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_screenutil: ^5.9.0
  flutter_styled_toast: ^2.2.1
  intl: ^0.18.0
  animations: ^2.0.10
  google_fonts: ^6.1.0
  http: ^1.1.2
  skeletonizer: ^0.8.0

flutter:

  uses-material-design: true
